#!/bin/bash

## automatic exit from bash shell script on error
set -e

COMMAND="$1"
COMMAND_ARG="$2"

install() {
	docker pull ifnazar/sybase_15_7:v1
}

createContainer() {
	CURRENT_DIR="$(pwd)"
	DOCKER_EXTERNAL_DIR=${CURRENT_DIR}/sybase_data
	DOCKER_LOCAL_DATA=/opt/sybase/external_data

	if [ ! -d "$DIRECTORY" ]; then
	     mkdir -p  ${DOCKER_EXTERNAL_DIR}
	fi

	docker run -i -t  -v ${DOCKER_EXTERNAL_DIR}:${DOCKER_LOCAL_DATA} --name sybase-container -p 5000:5000 -h dksybase -d ifnazar/sybase_15_7:v1 bash /sybase/start >> /dev/null
}

start() {
	CURRENT_DOCKER_ID="$(docker ps -a -q --filter 'name=sybase-container')"
	if [ -n "$CURRENT_DOCKER_ID" ]; then
		docker start sybase-container
		echo ">>  sybase docker started"
	else
		createContainer
		echo ">>  sybase docker started"
	fi
}

stop() {
	CURRENT_DOCKER_ID="$(docker ps -q --filter 'name=sybase-container')"
	if [ ! -z "$CURRENT_DOCKER_ID" ]; then
	     echo ">>  stopping sybase docker"
	     timeout 20 docker exec sybase-container bash /sybase/stop >> /dev/null
	     sleep 1
	     timeout 20 docker stop sybase-container >> /dev/null
	     sleep 1
	fi
}

restart() {
	stop
	start
}

sql(){
	if [ ! -z "${COMMAND_ARG}" ];  then
	    SQL_FILE=/sybase/toRun.sql
	    docker cp "${COMMAND_ARG}" sybase-container:"${SQL_FILE}"
	    ISQL_ARGUMENT=-i"${SQL_FILE}"
	fi

	docker exec -i -t sybase-container bash /sybase/isql "${ISQL_ARGUMENT}"
}

run_bash(){
	docker exec -i -t sybase-container bash
}


case "${COMMAND}" in
    install)
        install
        ;;
    bash)
        run_bash
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    sql)
        sql
        ;;

    *)
        echo $"Usage: $0 {install|bash|start|stop|sql|restart}"
        exit 1
esac
exit 0

